service: tpt2-backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: default

functions:
  api:
    handler: index.handler
    events:
      - httpApi: 
          path: '/'
          method: ANY
      - httpApi: 
          path: '/path'
          method: GET

  facebookSignIn:
    handler: endpoints.auth.facebookAuth.signIn
    events: 
      - httpApi:
          path: '/facebook_signin'
          method: POST
