// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwQmlarDT5aHRDcURp0VfQL-rua3ME6lE',
    appId: '1:303559538310:web:ffa30046f38cb1ae30c307',
    messagingSenderId: '303559538310',
    projectId: 'intern-mobile-app-4220',
    authDomain: 'intern-mobile-app-4220.firebaseapp.com',
    storageBucket: 'intern-mobile-app-4220.appspot.com',
    measurementId: 'G-QP7BYCYV1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADP1YARbCLurxVICF7SRqPvgwCZ3CXUAE',
    appId: '1:303559538310:android:6c13b1ee55eba4c430c307',
    messagingSenderId: '303559538310',
    projectId: 'intern-mobile-app-4220',
    storageBucket: 'intern-mobile-app-4220.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1UV0N5IhqQCsuy6QpTKo7ZQRhj5sd-qM',
    appId: '1:303559538310:ios:5529d955716ead7030c307',
    messagingSenderId: '303559538310',
    projectId: 'intern-mobile-app-4220',
    storageBucket: 'intern-mobile-app-4220.appspot.com',
    iosClientId: '303559538310-j3g77jf37bmu00kq7brqbps0lvbrto0r.apps.googleusercontent.com',
    iosBundleId: 'com.example.internMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1UV0N5IhqQCsuy6QpTKo7ZQRhj5sd-qM',
    appId: '1:303559538310:ios:3cbf20b91a2c8f8730c307',
    messagingSenderId: '303559538310',
    projectId: 'intern-mobile-app-4220',
    storageBucket: 'intern-mobile-app-4220.appspot.com',
    iosClientId: '303559538310-03le960b3ql5o9h390ern93hl404q9cg.apps.googleusercontent.com',
    iosBundleId: 'com.example.internMobileApp.RunnerTests',
  );
}
